# Generated by Django 3.2.7 on 2022-12-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rating',
            new_name='rating_profile',
        ),
    ]
